// src/constants/schemes.js
// Static seed data — in production these come from Firestore.

export const SCHEMES = [
  {
    id: 'pm-awas-yojana',
    nameEn: 'PM Awas Yojana (Gramin)',
    nameHi: 'प्रधानमंत्री आवास योजना (ग्रामीण)',
    category: 'housing',
    type: 'central',
    benefitEn: 'Up to ₹1.30 lakh subsidy for constructing a permanent house',
    benefitHi: 'पक्का घर बनाने के लिए ₹१.३० लाख तक की सब्सिडी',
    amount: 130000,
    interestRate: null,
    eligibility: { maxIncome: 300000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Bank Passbook', 'Income Certificate', 'Ration Card', 'Land documents'],
    documentsHi: ['आधार कार्ड', 'बैंक पासबुक', 'आय प्रमाण पत्र', 'राशन कार्ड', 'भूमि दस्तावेज़'],
    stepsEn: ['Visit Gram Panchayat office', 'Fill application form', 'Submit documents', 'Verification by officer', 'Approval & fund transfer'],
    stepsHi: ['ग्राम पंचायत कार्यालय जाएँ', 'आवेदन पत्र भरें', 'दस्तावेज़ जमा करें', 'अधिकारी द्वारा सत्यापन', 'स्वीकृति और राशि हस्तांतरण'],
    officialUrl: 'https://pmayg.dord.gov.in/netiayHome/Home.aspx',
    deadlineDays: 45,
    icon: '🏠',
    tags: ['housing', 'rural', 'bpl'],
  },
  {
    id: 'ayushman-bharat',
    nameEn: 'Ayushman Bharat PM-JAY',
    nameHi: 'आयुष्मान भारत पीएम-जेएवाई',
    category: 'health',
    type: 'central',
    benefitEn: '₹5 lakh health insurance per family per year at empanelled hospitals',
    benefitHi: 'सूचीबद्ध अस्पतालों में प्रति परिवार प्रति वर्ष ₹५ लाख स्वास्थ्य बीमा',
    amount: 500000,
    eligibility: { maxIncome: 200000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 0 },
    documentsEn: ['Aadhar Card', 'Ration Card', 'PM-JAY e-card'],
    documentsHi: ['आधार कार्ड', 'राशन कार्ड', 'पीएम-जेएवाई ई-कार्ड'],
    stepsEn: ['Visit pmjay.gov.in', 'Check eligibility by mobile number', 'Get Golden Card from CSC centre', 'Show card at empanelled hospital'],
    stepsHi: ['pmjay.gov.in पर जाएँ', 'मोबाइल नंबर से पात्रता जाँचें', 'सीएससी केंद्र से गोल्डन कार्ड लें', 'सूचीबद्ध अस्पताल में कार्ड दिखाएँ'],
    officialUrl: 'https://pmjay.gov.in',
    deadlineDays: null,
    icon: '🏥',
    tags: ['health', 'insurance', 'hospital'],
  },
  {
    id: 'pm-kisan',
    nameEn: 'PM Kisan Samman Nidhi',
    nameHi: 'प्रधानमंत्री किसान सम्मान निधि',
    category: 'farmer',
    type: 'central',
    benefitEn: '₹6,000 per year in 3 installments of ₹2,000 directly to bank account',
    benefitHi: '₹६,०००/वर्ष, तीन किस्तों में ₹२,०००, सीधे बैंक खाते में',
    amount: 6000,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'farmer', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Bank Account', 'Land Records', 'Mobile Number'],
    documentsHi: ['आधार कार्ड', 'बैंक खाता', 'भूमि अभिलेख', 'मोबाइल नंबर'],
    stepsEn: ['Visit pmkisan.gov.in', 'Click New Farmer Registration', 'Enter Aadhar and land details', 'Submit for verification', 'Money credited in 3-4 weeks'],
    stepsHi: ['pmkisan.gov.in पर जाएँ', 'नया किसान पंजीकरण पर क्लिक करें', 'आधार और भूमि विवरण दर्ज करें', 'सत्यापन के लिए जमा करें', '३-४ सप्ताह में राशि क्रेडिट'],
    officialUrl: 'https://pmkisan.gov.in',
    deadlineDays: null,
    icon: '🌾',
    tags: ['farmer', 'income', 'direct-benefit'],
  },
  {
    id: 'mudra-yojana',
    nameEn: 'PM Mudra Yojana',
    nameHi: 'प्रधानमंत्री मुद्रा योजना',
    category: 'loan',
    type: 'central',
    benefitEn: 'Business loans from ₹50,000 to ₹10 lakh without collateral',
    benefitHi: 'बिना गारंटी के ₹५०,००० से ₹१० लाख तक का व्यवसाय ऋण',
    amount: 1000000,
    interestRate: '8-12%',
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 65, minAge: 18 },
    documentsEn: ['Aadhar Card', 'PAN Card', 'Business Plan', 'Bank Statement', 'Passport photo'],
    documentsHi: ['आधार कार्ड', 'पैन कार्ड', 'व्यवसाय योजना', 'बैंक विवरण', 'पासपोर्ट फ़ोटो'],
    stepsEn: ['Choose tier: Shishu/Kishore/Tarun', 'Visit any bank or MFI', 'Submit application with documents', 'Bank processes in 7-10 days'],
    stepsHi: ['श्रेणी चुनें: शिशु/किशोर/तरुण', 'किसी भी बैंक या एमएफआई पर जाएँ', 'दस्तावेज़ के साथ आवेदन जमा करें', 'बैंक ७-१० दिनों में प्रक्रिया करेगा'],
    officialUrl: 'https://www.mudra.org.in',
    deadlineDays: null,
    icon: '💼',
    tags: ['loan', 'business', 'msme', 'entrepreneur'],
  },
  {
    id: 'skill-india',
    nameEn: 'Pradhan Mantri Kaushal Vikas Yojana',
    nameHi: 'प्रधानमंत्री कौशल विकास योजना',
    category: 'education',
    type: 'central',
    benefitEn: 'Free skill training + government certificate + placement assistance',
    benefitHi: 'निःशुल्क कौशल प्रशिक्षण + सरकारी प्रमाण पत्र + नौकरी सहायता',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 45, minAge: 15 },
    documentsEn: ['Aadhar Card', '10th Marksheet or equivalent', 'Bank Account'],
    documentsHi: ['आधार कार्ड', '१०वीं अंकपत्र या समकक्ष', 'बैंक खाता'],
    stepsEn: ['Visit skillindia.gov.in', 'Register with Aadhar', 'Choose nearest training centre', 'Complete 3-6 month course', 'Appear for assessment'],
    stepsHi: ['skillindia.gov.in पर जाएँ', 'आधार से पंजीकरण करें', 'निकटतम प्रशिक्षण केंद्र चुनें', '३-६ महीने का कोर्स पूरा करें', 'मूल्यांकन में बैठें'],
    officialUrl: 'https://www.skillindia.gov.in',
    deadlineDays: null,
    icon: '🎓',
    tags: ['education', 'skill', 'training', 'youth'],
  },
  {
    id: 'jan-dhan',
    nameEn: 'Pradhan Mantri Jan Dhan Yojana',
    nameHi: 'प्रधानमंत्री जन धन योजना',
    category: 'financial',
    type: 'central',
    benefitEn: 'Zero balance bank account + ₹2 lakh accident insurance + overdraft facility',
    benefitHi: 'शून्य बैलेंस बैंक खाता + ₹२ लाख दुर्घटना बीमा + ओवरड्राफ्ट सुविधा',
    amount: 200000,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 10 },
    documentsEn: ['Aadhar Card or any ID proof', 'Passport photo'],
    documentsHi: ['आधार कार्ड या कोई भी पहचान प्रमाण', 'पासपोर्ट फ़ोटो'],
    stepsEn: ['Visit nearest bank branch', 'Ask for Jan Dhan account', 'Fill form with ID proof', 'Account opens same day'],
    stepsHi: ['निकटतम बैंक शाखा जाएँ', 'जन धन खाते के लिए पूछें', 'पहचान प्रमाण के साथ फ़ॉर्म भरें', 'उसी दिन खाता खुलता है'],
    officialUrl: 'https://pmjdy.gov.in',
    deadlineDays: null,
    icon: '🏦',
    tags: ['banking', 'insurance', 'financial-inclusion'],
  },
  {
    id: 'ujjwala-yojana',
    nameEn: 'PM Ujjwala Yojana',
    nameHi: 'प्रधानमंत्री उज्ज्वला योजना',
    category: 'women',
    type: 'central',
    benefitEn: 'Free LPG connection with first cylinder and stove to BPL women',
    benefitHi: 'बीपीएल महिलाओं को पहले सिलेंडर और चूल्हे के साथ निःशुल्क एलपीजी कनेक्शन',
    amount: 1600,
    eligibility: { maxIncome: 200000, states: 'all', gender: 'female', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'BPL ration card', 'Bank account', 'Passport photo'],
    documentsHi: ['आधार कार्ड', 'बीपीएल राशन कार्ड', 'बैंक खाता', 'पासपोर्ट फ़ोटो'],
    stepsEn: ['Visit nearest LPG distributor', 'Fill Ujjwala application form', 'Submit BPL documents', 'Get connection in 3-5 days'],
    stepsHi: ['निकटतम एलपीजी वितरक पर जाएँ', 'उज्ज्वला आवेदन पत्र भरें', 'बीपीएल दस्तावेज़ जमा करें', '३-५ दिनों में कनेक्शन मिलेगा'],
    officialUrl: 'https://www.pmuy.gov.in',
    deadlineDays: null,
    icon: '🔥',
    tags: ['women', 'bpl', 'cooking', 'lpg'],
  },
  {
    id: 'kcc',
    nameEn: 'Kisan Credit Card (KCC)',
    nameHi: 'किसान क्रेडिट कार्ड (केसीसी)',
    category: 'loan',
    type: 'central',
    benefitEn: 'Crop loans up to ₹3 lakh at only 4% interest rate per year',
    benefitHi: 'केवल ४% वार्षिक ब्याज दर पर ₹३ लाख तक का फसल ऋण',
    amount: 300000,
    interestRate: '4%',
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'farmer', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Land Records (Khasra)', 'Bank Account', 'Passport photo'],
    documentsHi: ['आधार कार्ड', 'भूमि अभिलेख (खसरा)', 'बैंक खाता', 'पासपोर्ट फ़ोटो'],
    stepsEn: ['Visit nearest bank (SBI/PNB/Cooperative)', 'Ask for KCC application', 'Submit land documents', 'Credit limit set in 2 weeks'],
    stepsHi: ['निकटतम बैंक जाएँ (एसबीआई/पीएनबी/सहकारी)', 'केसीसी आवेदन माँगें', 'भूमि दस्तावेज़ जमा करें', '२ सप्ताह में ऋण सीमा तय होगी'],
    officialUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    deadlineDays: null,
    icon: '💳',
    tags: ['farmer', 'loan', 'credit', 'agriculture'],
  },
  {
    id: 'sukanya-samriddhi',
    nameEn: 'Sukanya Samriddhi Yojana',
    nameHi: 'सुकन्या समृद्धि योजना',
    category: 'financial',
    type: 'central',
    benefitEn: 'High interest rate savings for girl child education and marriage',
    benefitHi: 'बालिका शिक्षा और विवाह के लिए उच्च ब्याज दर',
    amount: 0,
    interestRate: '8.2%',
    eligibility: { maxIncome: null, states: 'all', gender: 'female', occupation: 'all', maxAge: 10, minAge: 0 },
    documentsEn: ['Girl child birth certificate', 'Parent Aadhar Card', 'Parent PAN Card'],
    documentsHi: ['बालिका जन्म प्रमाण पत्र', 'माता-पिता का आधार कार्ड', 'माता-पिता का पैन कार्ड'],
    stepsEn: ['Visit nearest Post Office or Bank', 'Fill SSY account opening form', 'Submit documents and deposit minimum ₹250'],
    stepsHi: ['निकटतम डाकघर या बैंक जाएँ', 'एसएसवाई खाता खोलने का फॉर्म भरें', 'दस्तावेज़ जमा करें और न्यूनतम ₹250 जमा करें'],
    officialUrl: 'https://www.indiapost.gov.in',
    deadlineDays: null,
    icon: '👧',
    tags: ['girl', 'savings', 'education'],
  },
  {
    id: 'atal-pension',
    nameEn: 'Atal Pension Yojana',
    nameHi: 'अटल पेंशन योजना',
    category: 'senior',
    type: 'central',
    benefitEn: 'Guaranteed pension of ₹1000 to ₹5000 per month after age 60',
    benefitHi: '60 वर्ष की आयु के बाद ₹1000 से ₹5000 प्रति माह की गारंटीड पेंशन',
    amount: 5000,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 40, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Savings Bank Account'],
    documentsHi: ['आधार कार्ड', 'बचत बैंक खाता'],
    stepsEn: ['Visit your bank branch', 'Fill APY registration form', 'Provide Aadhar and auto-debit approval'],
    stepsHi: ['अपनी बैंक शाखा में जाएँ', 'एपीवाई पंजीकरण फॉर्म भरें', 'आधार और ऑटो-डेबिट स्वीकृति प्रदान करें'],
    officialUrl: 'https://pfrda.org.in',
    deadlineDays: null,
    icon: '👴',
    tags: ['pension', 'senior', 'retirement'],
  },
  {
    id: 'mgnrega',
    nameEn: 'MGNREGA Job Scheme',
    nameHi: 'मनरेगा रोजगार योजना',
    category: 'farmer',
    type: 'central',
    benefitEn: 'Guaranteed 100 days of wage employment in a financial year to a rural household',
    benefitHi: 'ग्रामीण परिवार को एक वित्तीय वर्ष में 100 दिनों के 100% रोजगार की गारंटी',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Bank Account', 'Passport Photo', 'Job Card Application'],
    documentsHi: ['आधार कार्ड', 'बैंक खाता', 'पासपोर्ट फोटो', 'जॉब कार्ड आवेदन'],
    stepsEn: ['Visit local Gram Panchayat', 'Apply for a Job Card', 'Submit application for work', 'Work provided within 15 days'],
    stepsHi: ['स्थानीय ग्राम पंचायत में जाएँ', 'जॉब कार्ड के लिए आवेदन करें', 'काम के लिए आवेदन जमा करें', '15 दिनों के भीतर काम प्रदान किया गया'],
    officialUrl: 'https://nrega.nic.in',
    deadlineDays: null,
    icon: '⚒️',
    tags: ['job', 'employment', 'rural', 'wage'],
  },
  {
    id: 'pm-svanidhi',
    nameEn: 'PM SVANidhi',
    nameHi: 'पीएम स्वनिधि',
    category: 'loan',
    type: 'central',
    benefitEn: 'Collateral free working capital loan up to ₹10,000 for street vendors',
    benefitHi: 'रेहड़ी-पटरी वालों के लिए ₹10,000 तक का संपार्श्विक मुक्त कार्यशील पूंजी ऋण',
    amount: 10000,
    interestRate: '7% Subsidy',
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Voter ID', 'Certificate of Vending'],
    documentsHi: ['आधार कार्ड', 'वोटर आईडी', 'वेंडिंग का प्रमाण पत्र'],
    stepsEn: ['Visit pmsvanidhi.mohua.gov.in', 'Verify mobile number', 'Fill application out', 'Submit to nearest lending institution'],
    stepsHi: ['pmsvanidhi.mohua.gov.in पर जाएँ', 'मोबाइल नंबर सत्यापित करें', 'आवेदन भरें', 'निकटतम ऋण देने वाली संस्था को जमा करें'],
    officialUrl: 'https://www.pmsvanidhi.mohua.gov.in/',
    deadlineDays: null,
    icon: '🛒',
    tags: ['business', 'vendors', 'loan', 'urban'],
  },
  {
    id: 'pm-fasal-bima',
    nameEn: 'PM Fasal Bima Yojana',
    nameHi: 'प्रधानमंत्री फसल बीमा योजना',
    category: 'farmer',
    type: 'central',
    benefitEn: 'Insurance cover against crop failure due to natural calamities, pests or diseases',
    benefitHi: 'प्राकृतिक आपदाओं, कीटों या बीमारियों के कारण फसल बर्बाद होने पर बीमा कवर',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'farmer', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Land Records', 'Bank Passbook', 'Sowing Certificate'],
    documentsHi: ['आधार कार्ड', 'भूमि अभिलेख', 'बैंक पासबुक', 'बुवाई प्रमाण पत्र'],
    stepsEn: ['Visit pmfby.gov.in or nearest Bank', 'Apply within 10 days of sowing', 'Pay small premium (1.5-2%)', 'Claim if crop is damaged'],
    stepsHi: ['pmfby.gov.in या निकटतम बैंक जाएँ', 'बुवाई के 10 दिनों के भीतर आवेदन करें', 'छोटा प्रीमियम (1.5-2%) भरें', 'फसल खराब होने पर दावा करें'],
    officialUrl: 'https://pmfby.gov.in',
    deadlineDays: 10,
    icon: '⛈️',
    tags: ['farmer', 'insurance', 'crop', 'disaster'],
  },
  {
    id: 'pmay-urban',
    nameEn: 'PM Awas Yojana (Urban)',
    nameHi: 'प्रधानमंत्री आवास योजना (शहरी)',
    category: 'housing',
    type: 'central',
    benefitEn: 'Credit linked subsidy up to ₹2.67 lakh for buying or constructing home in urban areas',
    benefitHi: 'शहरी क्षेत्रों में घर खरीदने या बनाने के लिए ₹2.67 लाख तक की क्रेडिट लिंक्ड सब्सिडी',
    amount: 267000,
    eligibility: { maxIncome: 1800000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Income Proof', 'Property Registration', 'Bank Passbook'],
    documentsHi: ['आधार कार्ड', 'आय प्रमाण', 'संपत्ति का पंजीकरण', 'बैंक पासबुक'],
    stepsEn: ['Apply via bank or CND', 'Submit loan and PMAY application', 'Verification step', 'Subsidy credited directly to loan account'],
    stepsHi: ['बैंक या सीएनडी के माध्यम से आवेदन करें', 'ऋण और पीएमएवाई आवेदन जमा करें', 'सत्यापन', 'सब्सिडी सीधे ऋण खाते में जमा की गई'],
    officialUrl: 'https://pmaymis.gov.in',
    deadlineDays: null,
    icon: '🏢',
    tags: ['housing', 'urban', 'subsidy'],
  },
  {
    id: 'ddauy',
    nameEn: 'Deen Dayal Antyodaya Yojana',
    nameHi: 'दीन दयाल अंत्योदय योजना',
    category: 'housing',
    type: 'central',
    benefitEn: 'Provides shelter and essential services to urban homeless',
    benefitHi: 'शहरी बेघरों को आश्रय और आवश्यक सेवाएं प्रदान करता है',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 0 },
    documentsEn: ['No hard documents required for homeless shelters'],
    documentsHi: ['रैन बसेरों के लिए कोई दस्तावेज़ आवश्यक नहीं'],
    stepsEn: ['Locate a DAY-NULM shelter', 'Walk in or contact urban local bodies', 'Register at the shelter'],
    stepsHi: ['DAY-NULM आश्रय का पता लगाएं', 'शहरी स्थानीय निकायों से संपर्क करें', 'आश्रय में पंजीकरण करें'],
    officialUrl: 'https://nulm.gov.in',
    deadlineDays: null,
    icon: '🛏️',
    tags: ['housing', 'homeless', 'urban'],
  },
  {
    id: 'esic-scheme',
    nameEn: 'ESIC Health Insurance',
    nameHi: 'ईएसआईसी स्वास्थ्य बीमा',
    category: 'health',
    type: 'central',
    benefitEn: 'Complete medical care for workers and dependents (wages ≤ ₹21,000/month)',
    benefitHi: 'श्रमिकों और आश्रितों के लिए पूर्ण चिकित्सा देखभाल (वेतन ≤ ₹21,000/माह)',
    amount: 0,
    eligibility: { maxIncome: 252000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['ESIC Pehchan Card', 'Aadhar Card', 'Salary Slip'],
    documentsHi: ['ईएसआईसी पहचान कार्ड', 'आधार कार्ड', 'वेतन पर्ची'],
    stepsEn: ['Employer registers employee on ESIC portal', 'Get Pehchan Card', 'Visit ESIC dispensary/hospital for free treatment'],
    stepsHi: ['नियोक्ता कर्मचारी को ईएसआईसी पोर्टल पर पंजीकृत करता है', 'पहचान कार्ड लें', 'मुफ़्त इलाज के लिए ईएसआईसी अस्पताल जाएँ'],
    officialUrl: 'https://www.esic.gov.in',
    deadlineDays: null,
    icon: '🩺',
    tags: ['health', 'insurance', 'workers'],
  },
  {
    id: 'pm-surakshit-matritva',
    nameEn: 'PM Surakshit Matritva Abhiyan',
    nameHi: 'पीएम सुरक्षित মাতृत्व अभियान',
    category: 'health',
    type: 'central',
    benefitEn: 'Free health checkups and treatments for pregnant women on 9th of every month',
    benefitHi: 'गर्भवती महिलाओं के लिए हर महीने की 9 तारीख को मुफ्त स्वास्थ्य जांच और उपचार',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'female', occupation: 'all', maxAge: 50, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Pregnancy confirmation / MCP Card'],
    documentsHi: ['आधार कार्ड', 'गर्भावस्था की पुष्टि / एमसीपी कार्ड'],
    stepsEn: ['Visit any Govt Hospital on the 9th of month', 'Show MCP card', 'Get free ultrasound, blood tests and medicines'],
    stepsHi: ['महीने की 9 तारीख को किसी भी सरकारी अस्पताल में जाएँ', 'एमसीपी कार्ड दिखाएं', 'मुफ्त परीक्षण और दवाएं प्राप्त करें'],
    officialUrl: 'https://pmsma.mohfw.gov.in/',
    deadlineDays: null,
    icon: '🤰',
    tags: ['health', 'women', 'pregnancy', 'maternal'],
  },
  {
    id: 'nmms-scholarship',
    nameEn: 'National Means cum Merit Scholarship',
    nameHi: 'राष्ट्रीय साधन सह योग्यता छात्रवृत्ति',
    category: 'education',
    type: 'central',
    benefitEn: '₹12,000 per annum for students studying in classes 9th to 12th',
    benefitHi: 'कक्षा 9वीं से 12वीं में पढ़ने वाले छात्रों के लिए ₹12,000 प्रति वर्ष',
    amount: 12000,
    eligibility: { maxIncome: 350000, states: 'all', gender: 'all', occupation: 'all', maxAge: 18, minAge: 13 },
    documentsEn: ['Aadhar Card', 'Income Certificate', 'Class 8 Marksheet', 'Bank Passbook'],
    documentsHi: ['आधार कार्ड', 'आय प्रमाण पत्र', 'कक्षा 8 की मार्कशीट', 'बैंक पासबुक'],
    stepsEn: ['Must pass state level examination', 'Apply via National Scholarship Portal', 'Amount credited to verified bank account'],
    stepsHi: ['राज्य स्तरीय परीक्षा उत्तीर्ण करनी होगी', 'NSP पोर्टल के माध्यम से आवेदन करें', 'राशि बैंक खाते में जमा'],
    officialUrl: 'https://scholarships.gov.in',
    deadlineDays: null,
    icon: '🎒',
    tags: ['education', 'scholarship', 'students'],
  },
  {
    id: 'pm-shri',
    nameEn: 'PM SHRI Schools',
    nameHi: 'पीएम श्री विद्यालय',
    category: 'education',
    type: 'central',
    benefitEn: 'Modern, high-quality, holistic education at upgraded government schools',
    benefitHi: 'उन्नत सरकारी स्कूलों में आधुनिक, उच्च गुणवत्ता वाली समग्र शिक्षा',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 18, minAge: 5 },
    documentsEn: ['Birth Certificate', 'Aadhar Card', 'Previous School TC (if any)'],
    documentsHi: ['जन्म प्रमाण पत्र', 'आधार कार्ड', 'पिछला स्कूल टीसी (यदि कोई हो)'],
    stepsEn: ['Locate a PM SHRI school nearby', 'Register during admission season', 'Complete standard admission process'],
    stepsHi: ['आसपास के पीएम श्री विद्यालय का पता लगाएं', 'प्रवेश के मौसम के दौरान पंजीकरण करें', 'प्रवेश प्रक्रिया पूरी करें'],
    officialUrl: 'https://pmshri.education.gov.in',
    deadlineDays: null,
    icon: '🏫',
    tags: ['education', 'school', 'children'],
  },
  {
    id: 'pm-matru-vandana',
    nameEn: 'PM Matru Vandana Yojana',
    nameHi: 'पीएम मातृ वंदना योजना',
    category: 'women',
    type: 'central',
    benefitEn: 'Maternity benefit of ₹5,000 for first living child, ₹6,000 for second child (if girl)',
    benefitHi: 'पहले जीवित बच्चे के लिए ₹5,000, दूसरे बच्चे (यदि लड़की हो) के लिए ₹6,000 का मातृत्व लाभ',
    amount: 5000,
    eligibility: { maxIncome: 800000, states: 'all', gender: 'female', occupation: 'all', maxAge: null, minAge: 19 },
    documentsEn: ['Aadhar Card', 'MCP Card from Anganwadi', 'Bank Account Details'],
    documentsHi: ['आधार कार्ड', 'आंगनवाड़ी से एमसीपी कार्ड', 'बैंक खाता विवरण'],
    stepsEn: ['Register pregnancy at local Anganwadi/ASHA', 'Fill PMMVY forms', 'Receive cash instantly in 2-3 installments'],
    stepsHi: ['स्थानीय आंगनवाड़ी में गर्भावस्था दर्ज करें', 'PMMVY फॉर्म भरें', 'किश्तों में तुरंत नकद प्राप्त करें'],
    officialUrl: 'https://pmmvy.wcd.gov.in',
    deadlineDays: 150, // Register within 150 days of LMP
    icon: '🤱',
    tags: ['women', 'maternity', 'cash'],
  },
  {
    id: 'beti-bachao',
    nameEn: 'Beti Bachao Beti Padhao',
    nameHi: 'बेटी बचाओ बेटी पढ़ाओ',
    category: 'women',
    type: 'central',
    benefitEn: 'Awareness, protection, and promotion of girl child education & rights',
    benefitHi: 'बालिका शिक्षा और अधिकारों के प्रति जागरूकता, संरक्षण और प्रचार',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'female', occupation: 'all', maxAge: null, minAge: 0 },
    documentsEn: ['Birth Certificate (for linked direct benefits)'],
    documentsHi: ['जन्म प्रमाण पत्र'],
    stepsEn: ['Contact local district women officer', 'Enroll in girl child protection drives', 'Connect to Sukanya Samriddhi via BBBP hubs'],
    stepsHi: ['स्थानीय जिला महिला अधिकारी से संपर्क करें', 'अभियानों में शामिल हों', 'हब के माध्यम से जुड़ें'],
    officialUrl: 'https://www.pmindia.gov.in/hi/government_tr_rec/%E0%A4%AC%E0%A5%87%E0%A4%9F%E0%A5%80-%E0%A4%AC%E0%A4%9A%E0%A4%BE%E0%A4%93-%E0%A4%AC%E0%A5%87%E0%A4%9F%E0%A5%80-%E0%A4%AA%E0%A4%A2%E0%A4%BC%E0%A4%BE%E0%A4%93-%E0%A4%AC%E0%A4%BE%E0%A4%B2/',
    deadlineDays: null,
    icon: '👨‍👩‍👧',
    tags: ['women', 'girl', 'rights', 'education'],
  },
  {
    id: 'ignoaps-pension',
    nameEn: 'National Old Age Pension Scheme',
    nameHi: 'राष्ट्रीय वृद्धावस्था पेंशन योजना',
    category: 'senior',
    type: 'central',
    benefitEn: 'Monthly pension of ₹200 (age 60+) and ₹500 (age 80+) for BPL citizens',
    benefitHi: 'बीपीएल नागरिकों के लिए प्रति माह ₹200 (60+ आयु) और ₹500 (80+ आयु) की पेंशन',
    amount: 200,
    eligibility: { maxIncome: 50000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 60 },
    documentsEn: ['Age Proof', 'BPL Ration Card', 'Aadhar Card', 'Bank Passbook'],
    documentsHi: ['आयु प्रमाण', 'बीपीएल राशन कार्ड', 'आधार कार्ड', 'बैंक पासबुक'],
    stepsEn: ['Obtain forms from Gram Panchayat/Municipality', 'Submit age and BPL proofs', 'Pension credited directly to bank/post office'],
    stepsHi: ['ग्राम पंचायत/नगर पालिका से फॉर्म प्राप्त करें', 'आयु और बीपीएल प्रमाण जमा करें', 'पेंशन सीधे खाते में जमा होगी'],
    officialUrl: 'https://nsap.nic.in',
    deadlineDays: null,
    icon: '🧓',
    tags: ['senior', 'pension', 'bpl'],
  },
  {
    id: 'rashtriya-vayoshri',
    nameEn: 'Rashtriya Vayoshri Yojana',
    nameHi: 'राष्ट्रीय वयोश्री योजना',
    category: 'senior',
    type: 'central',
    benefitEn: 'Free physical aids/assisted-living devices (hearing aids, wheelchairs) for BPL seniors',
    benefitHi: 'बीपीएल वरिष्ठ नागरिकों के लिए मुफ्त भौतिक सहायता/उपकरण (व्हीलचेयर, श्रवण यंत्र)',
    amount: 0,
    eligibility: { maxIncome: 180000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 60 },
    documentsEn: ['Aadhar Card', 'BPL Card / Income Proof', 'Medical Certificate of impairment'],
    documentsHi: ['आधार कार्ड', 'बीपीएल कार्ड / आय प्रमाण', 'हानि का चिकित्सा प्रमाण पत्र'],
    stepsEn: ['Attend ALIMCO distribution camp', 'Submit age/income proof and medical cert', 'Get device prescribed on the spot'],
    stepsHi: ['शिविर में भाग लें', 'प्रमाण जमा करें', 'मौके पर उपकरण प्राप्त करें'],
    officialUrl: 'https://socialjustice.gov.in/schemes',
    deadlineDays: null,
    icon: '🦽',
    tags: ['senior', 'disability', 'equipment'],
  },
  {
    id: 'adip-scheme',
    nameEn: 'ADIP Scheme',
    nameHi: 'एडीआईपी योजना',
    category: 'disability',
    type: 'central',
    benefitEn: 'Free/subsidized assisting devices (tricycles, prosthetics) for Divyangjan',
    benefitHi: 'दिव्यांगजनों के लिए मुफ्त/सब्सिडी वाले सहायक उपकरण',
    amount: 0,
    eligibility: { maxIncome: 270000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 0 },
    documentsEn: ['Disability Certificate (40%+)', 'Income Certificate', 'Aadhar Card'],
    documentsHi: ['विकलांगता प्रमाण पत्र (40%+)', 'आय प्रमाण पत्र', 'आधार कार्ड'],
    stepsEn: ['Apply through ALIMCO or common service centres', 'Provide 40%+ disability cert', 'Collect device at distribution camps'],
    stepsHi: ['सीएससी के माध्यम से आवेदन करें', 'प्रमाण पत्र प्रदान करें', 'वितरण शिविरों से उपकरण लें'],
    officialUrl: 'https://adip.depwd.gov.in/',
    deadlineDays: null,
    icon: '🦯',
    tags: ['disability', 'equipment', 'rehab'],
  },
  {
    id: 'igndps-pension',
    nameEn: 'National Disability Pension Scheme',
    nameHi: 'राष्ट्रीय विकलांगता पेंशन योजना',
    category: 'disability',
    type: 'central',
    benefitEn: '₹300 monthly pension for persons with multiple/severe disabilities from BPL families',
    benefitHi: 'बीपीएल परिवारों के गंभीर विकलांग व्यक्तियों के लिए ₹300 मासिक पेंशन',
    amount: 300,
    eligibility: { maxIncome: 50000, states: 'all', gender: 'all', occupation: 'all', maxAge: 79, minAge: 18 },
    documentsEn: ['Severe Disability Certificate (80%+)', 'BPL Card', 'Bank Passbook'],
    documentsHi: ['गंभीर विकलांगता प्रमाण पत्र (80%+)', 'बीपीएल कार्ड', 'बैंक पासबुक'],
    stepsEn: ['Submit application to block/municipal office', 'Officer verifies severity', 'Amount credited monthly via DBT'],
    stepsHi: ['कार्यालय में आवेदन जमा करें', 'अधिकारी गंभीरता की पुष्टि करता है', 'मासिक रूप से श्रेय दिया जाता है'],
    officialUrl: 'https://services.india.gov.in/service/listing?cat_id=42&ln=en',
    deadlineDays: null,
    icon: '🦼',
    tags: ['disability', 'pension', 'bpl'],
  },
  {
    id: 'sugamya-bharat',
    nameEn: 'Accessible India Campaign',
    nameHi: 'सुगम्य भारत अभियान',
    category: 'disability',
    type: 'central',
    benefitEn: 'Ensures barrier-free accessible environments (buildings, transport, websites) for PwDs',
    benefitHi: 'दिव्यांगजनों के लिए बाधा मुक्त सुलभ वातावरण (भवन, परिवहन, वेबसाइट) सुनिश्चित करता है',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 0 },
    documentsEn: ['N/A (Universal accessibility initiative)'],
    documentsHi: ['कोई नहीं (सार्वभौमिक पहुंच पहल)'],
    stepsEn: ['Use Sugamya Bharat App to report inaccessible public infrastructure', 'Govt takes corrective action'],
    stepsHi: ['सार्वजनिक बुनियादी ढांचे की रिपोर्ट करने के लिए ऐप का उपयोग करें', 'सरकार कार्रवाई करती है'],
    officialUrl: 'https://disabilityaffairs.gov.in',
    deadlineDays: null,
    icon: '🏢',
    tags: ['disability', 'accessibility', 'infrastructure'],
  },
  {
    id: 'pm-suraksha-bima',
    nameEn: 'PM Suraksha Bima Yojana',
    nameHi: 'पीएम सुरक्षा बीमा योजना',
    category: 'financial',
    type: 'central',
    benefitEn: '₹2 lakh accidental death and full disability cover for just ₹20 per year',
    benefitHi: 'केवल ₹20 प्रति वर्ष में ₹2 लाख का आकस्मिक मृत्यु और पूर्ण विकलांगता कवर',
    amount: 200000,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 70, minAge: 18 },
    documentsEn: ['Bank Passbook', 'Aadhar Card'],
    documentsHi: ['बैंक पासबुक', 'आधार कार्ड'],
    stepsEn: ['Maintain active bank account', 'Opt-in via net banking or branch visit', '₹20 auto-debited late May every year'],
    stepsHi: ['सक्रिय बैंक खाता बनाए रखें', 'नेट बैंकिंग या शाखा के माध्यम से ऑप्ट-इन करें', 'हर साल ₹20 ऑटो-डेबिट होते हैं'],
    officialUrl: 'https://jansuraksha.gov.in',
    deadlineDays: null,
    deadlineDays: null,
    icon: '🛡️',
    tags: ['financial', 'insurance', 'accident'],
  },
  {
    id: 'pmegp',
    nameEn: 'PM Employment Generation Programme',
    nameHi: 'प्रधानमंत्री रोजगार सृजन कार्यक्रम',
    category: 'job',
    type: 'central',
    benefitEn: 'Subsidy up to 35% on projects up to ₹50 lakh for manufacturing and ₹20 lakh for services',
    benefitHi: 'विनिर्माण के लिए ₹50 लाख और सेवाओं के लिए ₹20 लाख तक की परियोजनाओं पर 35% तक की सब्सिडी',
    amount: 5000000,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar Card', 'Project Report', 'Education/Skill Certificate', 'Bank Account'],
    documentsHi: ['आधार कार्ड', 'परियोजना रिपोर्ट', 'शिक्षा/कौशल प्रमाण पत्र', 'बैंक खाता'],
    stepsEn: ['Apply online at kviconline.gov.in', 'Submit project report', 'Bank approves loan and KVIC releases margin money'],
    stepsHi: ['kviconline.gov.in पर ऑनलाइन आवेदन करें', 'परियोजना रिपोर्ट जमा करें', 'बैंक ऋण स्वीकृत करता है और KVIC मार्जिन मनी जारी करता है'],
    officialUrl: 'https://www.kviconline.gov.in/pmegpeportal',
    deadlineDays: null,
    icon: '💼',
    tags: ['job', 'employment', 'business', 'msme'],
  },
  {
    id: 'ddu-gky',
    nameEn: 'DDU Grameen Kaushalya Yojana',
    nameHi: 'डीडीयू ग्रामीण कौशल्य योजना',
    category: 'job',
    type: 'central',
    benefitEn: 'Free residential skill training with assured placement for rural youth',
    benefitHi: 'ग्रामीण युवाओं के लिए सुनिश्चित प्लेसमेंट के साथ मुफ्त आवासीय कौशल प्रशिक्षण',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: 35, minAge: 15 },
    documentsEn: ['Aadhar Card', 'BPL Card / Income Certificate', 'Education Certificates'],
    documentsHi: ['आधार कार्ड', 'बीपीएल कार्ड / आय प्रमाण पत्र', 'शिक्षा प्रमाण पत्र'],
    stepsEn: ['Find nearest DDU-GKY training centre', 'Enroll in a course', 'Complete training and get placed in private sector'],
    stepsHi: ['निकटतम प्रशिक्षण केंद्र खोजें', 'पाठ्यक्रम में नामांकन करें', 'प्रशिक्षण पूरा करें और निजी क्षेत्र में नौकरी पाएं'],
    officialUrl: 'https://kaushal.rural.gov.in/#/home',
    deadlineDays: null,
    icon: '👔',
    tags: ['job', 'skill', 'rural', 'youth'],
  },
  {
    id: 'ncs-portal',
    nameEn: 'National Career Service',
    nameHi: 'राष्ट्रीय कैरियर सेवा',
    category: 'job',
    type: 'central',
    benefitEn: 'Free bridge courses, vocational guidance, and direct employer matching',
    benefitHi: 'निःशुल्क ब्रिज कोर्स, व्यावसायिक मार्गदर्शन और नियोक्ताओं से सीधा मिलान',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 15 },
    documentsEn: ['Aadhar Card', 'Education Certificates', 'Resume/CV'],
    documentsHi: ['आधार कार्ड', 'शिक्षा प्रमाण पत्र', 'बायोडाटा/सीवी'],
    stepsEn: ['Register as jobseeker on ncs.gov.in', 'Build profile', 'Apply for vacancies directly'],
    stepsHi: ['ncs.gov.in पर नौकरीपेशा के रूप में पंजीकरण करें', 'प्रोफ़ाइल बनाएं', 'सीधे रिक्तियों के लिए आवेदन करें'],
    officialUrl: 'https://www.ncs.gov.in',
    deadlineDays: null,
    icon: '🌐',
    tags: ['job', 'employment', 'portal'],
  },
  {
    id: 'abry',
    nameEn: 'Aatmanirbhar Bharat Rojgar Yojana',
    nameHi: 'आत्मनिर्भर भारत रोजगार योजना',
    category: 'job',
    type: 'central',
    benefitEn: 'EPF subsidy for new employees earning less than ₹15,000 to boost employment',
    benefitHi: 'रोजगार को बढ़ावा देने के लिए ₹15,000 से कम कमाने वाले नए कर्मचारियों के लिए ईपीएफ सब्सिडी',
    amount: 0,
    eligibility: { maxIncome: 180000, states: 'all', gender: 'all', occupation: 'all', maxAge: null, minAge: 15 },
    documentsEn: ['Aadhar Card', 'UAN (Universal Account Number)'],
    documentsHi: ['आधार कार्ड', 'UAN (यूनिवर्सल अकाउंट नंबर)'],
    stepsEn: ['Employer must be registered with EPFO', 'Employee must not had EPF before', 'EPF share is credited directly'],
    stepsHi: ['नियोक्ता EPFO से पंजीकृत होना चाहिए', 'कर्मचारी के पास पहले EPF नहीं होना चाहिए', 'EPF हिस्सा सीधे जमा किया जाता है'],
    officialUrl: 'https://epfindia.gov.in',
    deadlineDays: null,
    icon: '📈',
    tags: ['job', 'pf', 'subsidy'],
  },
  {
    id: 'ignwps',
    nameEn: 'Indira Gandhi National Widow Pension',
    nameHi: 'इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना',
    category: 'women',
    type: 'central',
    benefitEn: 'Monthly pension of ₹300 for BPL widows aged 40-79 years',
    benefitHi: '40-79 वर्ष की बीपीएल विधवाओं के लिए ₹300 की मासिक पेंशन',
    amount: 300,
    eligibility: { maxIncome: 50000, states: 'all', gender: 'female', occupation: 'all', maxAge: 79, minAge: 40 },
    documentsEn: ['Aadhar Card', 'Husband Death Certificate', 'BPL Card', 'Bank Passbook'],
    documentsHi: ['आधार कार्ड', 'पति का मृत्यु प्रमाण पत्र', 'बीपीएल कार्ड', 'बैंक पासबुक'],
    stepsEn: ['Visit Gram Panchayat or block office', 'Submit application with proofs', 'Amount directly transferred to bank via DBT'],
    stepsHi: ['ग्राम पंचायत या ब्लॉक कार्यालय जाएँ', 'प्रमाणों के साथ आवेदन जमा करें', 'राशि सीधे बैंक में ट्रांसफर की जाती है'],
    officialUrl: 'https://nsap.nic.in',
    deadlineDays: null,
    icon: '🌸',
    tags: ['women', 'widow', 'pension', 'bpl'],
  },
  {
    id: 'nfbs',
    nameEn: 'National Family Benefit Scheme',
    nameHi: 'राष्ट्रीय परिवार लाभ योजना',
    category: 'women',
    type: 'central',
    benefitEn: 'Lump sum assistance of ₹20,000 on the death of the primary breadwinner',
    benefitHi: 'प्राथमिक कमाने वाले की मृत्यु पर ₹20,000 की एकमुश्त सहायता',
    amount: 20000,
    eligibility: { maxIncome: 50000, states: 'all', gender: 'female', occupation: 'all', maxAge: 59, minAge: 18 },
    documentsEn: ['Death Certificate of Breadwinner', 'BPL/Income Certificate', 'Aadhar Card', 'Bank Account'],
    documentsHi: ['कमाने वाले का मृत्यु प्रमाण पत्र', 'बीपीएल/आय प्रमाण पत्र', 'आधार कार्ड', 'बैंक खाता'],
    stepsEn: ['Apply through the District Social Welfare Office', 'Submit the application within 1 year of death', 'Grant will be credited to bank'],
    stepsHi: ['जिला समाज कल्याण कार्यालय के माध्यम से आवेदन करें', 'मृत्यु के 1 वर्ष के भीतर आवेदन जमा करें', 'अनुदान बैंक में जमा किया जाएगा'],
    officialUrl: 'https://sevasindhuservices.karnataka.gov.in/getServiceDesc.html?serviceId=5200014',
    deadlineDays: null,
    icon: '🛡️',
    tags: ['women', 'widow', 'family', 'assistance'],
  },
  {
    id: 'swadhar-greh',
    nameEn: 'Swadhar Greh Scheme',
    nameHi: 'स्वाधार गृह योजना',
    category: 'women',
    type: 'central',
    benefitEn: 'Shelter, food, clothing, and counseling for widows destitute and women in distress',
    benefitHi: 'निराश्रित विधवाओं और संकटग्रस्त महिलाओं के लिए आश्रय, भोजन, कपड़े और परामर्श',
    amount: 0,
    eligibility: { maxIncome: null, states: 'all', gender: 'female', occupation: 'all', maxAge: null, minAge: 18 },
    documentsEn: ['Aadhar/Identity Proof (if available)'],
    documentsHi: ['आधार/पहचान प्रमाण (यदि उपलब्ध हो)'],
    stepsEn: ['Contact local NGO or Women & Child Development officer', 'Walk-in to nearest Swadhar Greh shelter'],
    stepsHi: ['स्थानीय एनजीओ या महिला एवं बाल विकास अधिकारी से संपर्क करें', 'निकटतम स्वाधार गृह आश्रय में जाएं'],
    officialUrl: 'https://socialwelfare.vikaspedia.in/viewcontent/social-welfare/women-and-child-development/women-development-1/swadhar-greh?lgn=en',
    deadlineDays: null,
    icon: '🏡',
    tags: ['women', 'widow', 'shelter', 'food'],
  }
]

export const CATEGORIES = [
  { id: 'all',        labelEn: 'All',            labelHi: 'सभी',          icon: '◉' },
  { id: 'housing',   labelEn: 'Housing',         labelHi: 'आवास',         icon: '🏠' },
  { id: 'health',    labelEn: 'Health',          labelHi: 'स्वास्थ्य',    icon: '🏥' },
  { id: 'farmer',    labelEn: 'Farmer',          labelHi: 'किसान',        icon: '🌾' },
  { id: 'job',       labelEn: 'Jobs / Work',     labelHi: 'नौकरी / काम',   icon: '💼' },
  { id: 'education', labelEn: 'Education',       labelHi: 'शिक्षा',       icon: '🎓' },
  { id: 'women',     labelEn: 'Women',           labelHi: 'महिलाएँ',      icon: '👩' },
  { id: 'loan',      labelEn: 'Loans',           labelHi: 'ऋण',          icon: '💳' },
  { id: 'senior',    labelEn: 'Senior Citizens', labelHi: 'वरिष्ठ नागरिक', icon: '👴' },
  { id: 'disability',labelEn: 'Disability',      labelHi: 'विकलांगता',    icon: '♿' },
]

export const SITUATION_KEYWORDS = {
  farmer:     ['farmer', 'kisan', 'agriculture', 'crop', 'field', 'rain', 'destroyed', 'flood', 'drought', 'खेत', 'किसान', 'फसल', 'बारिश', 'बर्बाद', 'सूखा'],
  job:        ['job', 'unemployed', 'work', 'employment', 'vacancy', 'hiring', 'नौकरी', 'बेरोजगार', 'काम', 'रोजगार', 'भर्ती'],
  health:     ['sick', 'hospital', 'medical', 'disease', 'illness', 'treatment', 'surgery', 'बीमार', 'अस्पताल', 'दवा', 'इलाज', 'ऑपरेशन'],
  loan:       ['loan', 'money', 'borrow', 'debt', 'capital', 'credit', 'ऋण', 'पैसा', 'उधार', 'कर्ज', 'पूंजी'],
  women:      ['widow', 'woman', 'female', 'mother', 'girl', 'daughter', 'विधवा', 'महिला', 'माँ', 'लड़की', 'बेटी'],
  education:  ['student', 'study', 'school', 'college', 'course', 'degree', 'विद्यार्थी', 'पढ़ाई', 'स्कूल', 'कॉलेज', 'डिग्री'],
  housing:    ['house', 'home', 'shelter', 'rent', 'building', 'slum', 'jhuggi', 'घर', 'मकान', 'आवास', 'किराया', 'झुग्गी'],
}
